#!/usr/bin/env bash
# Writes the production settings for JobsNexGen:
#   ~/.jobsnexgen/secrets.env        secrets, generated once (new ones are added on later runs)
#   ~/.jobsnexgen/ecosystem.config.js the pm2 config that passes them to the apps
# Run by setup.sh and by every update.sh. Safe to re-run: existing secrets are kept.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
CONF="$HOME/.jobsnexgen"
SECRETS="$CONF/secrets.env"

randpw() { python3 -c "import secrets, string; a = string.ascii_letters + string.digits; print(''.join(secrets.choice(a) for _ in range($1)))"; }
add_secret() {  # $1 = name, $2 = value; only written if the name isn't there yet
  grep -q "^$1=" "$SECRETS" || (umask 077; echo "$1=$2" >> "$SECRETS")
}

mkdir -p "$CONF"
chmod 700 "$CONF"
(umask 077; touch "$SECRETS")
add_secret PORTAL_SECRET_KEY "$(openssl rand -hex 32)"
add_secret CRM_SECRET_KEY "$(openssl rand -hex 32)"
add_secret PORTAL_ADMIN_PASSWORD "$(randpw 16)"
add_secret CRM_OWNER_PASSWORD "$(randpw 16)"
add_secret SYNC_RECRUITER_EMAIL "crm-sync@jobsnexgen.com"
add_secret SYNC_RECRUITER_PASSWORD "$(randpw 20)"
# Shared by both apps: the CRM uses it to read new jobs and applicants from the portal
add_secret INTEGRATION_KEY "$(openssl rand -hex 32)"
# shellcheck disable=SC1090
source "$SECRETS"

# Production settings go in the process environment, which overrides the
# committed .env files (dev values + API keys) without editing them.
(umask 077; cat > "$CONF/ecosystem.config.js" <<ECOSYSTEM
// Generated by deploy/gcp/configure.sh. Holds production secrets; do not commit.
module.exports = {
  apps: [
    {
      name: "portal-api",
      cwd: "$REPO/backend",
      script: "$REPO/backend/venv/bin/python",
      args: "-m uvicorn app.main:app --host 127.0.0.1 --port 8000",
      interpreter: "none",
      env: {
        SECRET_KEY: "$PORTAL_SECRET_KEY",
        CORS_ORIGINS: "https://www.jobsnexgen.com,https://jobsnexgen.com",
        FRONTEND_URL: "https://www.jobsnexgen.com",
        DEBUG: "false",
        INTEGRATION_KEY: "$INTEGRATION_KEY",
      },
    },
    {
      name: "crm-api",
      cwd: "$REPO/crm/backend",
      script: "$REPO/crm/backend/venv/bin/python",
      args: "-m uvicorn app.main:app --host 127.0.0.1 --port 8001",
      interpreter: "none",
      env: {
        SECRET_KEY: "$CRM_SECRET_KEY",
        CORS_ORIGINS: "https://crm.jobsnexgen.com",
        FRONTEND_URL: "https://crm.jobsnexgen.com",
        DEBUG: "false",
        PORTAL_API_URL: "http://127.0.0.1:8000/api/v1",
        PORTAL_INTEGRATION_KEY: "$INTEGRATION_KEY",
        PORTAL_RECRUITER_EMAIL: "$SYNC_RECRUITER_EMAIL",
        PORTAL_RECRUITER_PASSWORD: "$SYNC_RECRUITER_PASSWORD",
      },
    },
    {
      name: "portal-web",
      cwd: "$REPO/frontend",
      script: "$REPO/frontend/node_modules/next/dist/bin/next",
      args: "start -p 3001 -H 127.0.0.1",
      env: {
        // Server-rendered pages (jobs list, job pages, sitemap) call the API inside the server
        API_INTERNAL_URL: "http://127.0.0.1:8000/api/v1",
      },
    },
    {
      name: "crm-web",
      cwd: "$REPO/crm/frontend",
      script: "$REPO/crm/frontend/node_modules/next/dist/bin/next",
      args: "start -p 3002 -H 127.0.0.1",
    },
  ],
};
ECOSYSTEM
)
echo "Settings written to $CONF (secrets kept from earlier runs)."
