#!/usr/bin/env bash
# One-time setup of JobsNexGen on a fresh Ubuntu 22.04 VM:
#   job portal -> www.jobsnexgen.com, CRM -> crm.jobsnexgen.com
# Usage, from the repo root on the VM:
#   bash deploy/gcp/setup.sh you@example.com
# Safe to re-run: generated secrets and passwords are kept in ~/.jobsnexgen.
set -euo pipefail

ADMIN_EMAIL="${1:?Usage: bash deploy/gcp/setup.sh <your-email>}"
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
CONF="$HOME/.jobsnexgen"

step() { echo; echo "==> $*"; }
randpw() { python3 -c "import secrets, string; a = string.ascii_letters + string.digits; print(''.join(secrets.choice(a) for _ in range($1)))"; }
# NEEDRESTART_MODE=a stops Ubuntu's "restart services?" prompt from pausing the install
apt_install() { sudo DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y "$@"; }

step "System packages"
sudo apt-get update -y
apt_install python3-venv python3-dev build-essential nginx certbot python3-certbot-nginx dnsutils git curl openssl

step "Node.js 22 and pm2"
if ! command -v node >/dev/null || [ "$(node -v | sed 's/^v//; s/\..*//')" -lt 20 ]; then
  # NodeSource's installer runs its own apt-get, so it needs the no-prompt settings too
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a bash -
  apt_install nodejs
fi
command -v pm2 >/dev/null || sudo npm install -g pm2

step "Swap space (Next.js builds need the headroom)"
if ! grep -q /swapfile /proc/swaps; then
  sudo fallocate -l 2G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
fi

step "Python virtualenvs"
for app in backend crm/backend; do
  [ -d "$REPO/$app/venv" ] || python3 -m venv "$REPO/$app/venv"
done

step "Production secrets (generated once, kept in $CONF)"
mkdir -p "$CONF"
chmod 700 "$CONF"
if [ ! -f "$CONF/secrets.env" ]; then
  (umask 077; cat > "$CONF/secrets.env" <<SECRETS
PORTAL_SECRET_KEY=$(openssl rand -hex 32)
CRM_SECRET_KEY=$(openssl rand -hex 32)
PORTAL_ADMIN_PASSWORD=$(randpw 16)
CRM_OWNER_PASSWORD=$(randpw 16)
SYNC_RECRUITER_EMAIL=crm-sync@jobsnexgen.com
SYNC_RECRUITER_PASSWORD=$(randpw 20)
SECRETS
  )
fi
# shellcheck disable=SC1091
source "$CONF/secrets.env"

step "pm2 app config"
# Production settings go in the process environment, which overrides the
# committed .env files (dev values + API keys) without editing them.
(umask 077; cat > "$CONF/ecosystem.config.js" <<ECOSYSTEM
// Generated by deploy/gcp/setup.sh. Holds production secrets; do not commit.
module.exports = {
  apps: [
    {
      name: "portal-api",
      cwd: "$REPO/backend",
      script: "$REPO/backend/venv/bin/python",
      args: "-m uvicorn app.main:app --host 127.0.0.1 --port 8000",
      interpreter: "none",
      env: {
        SECRET_KEY: "$PORTAL_SECRET_KEY",
        CORS_ORIGINS: "https://www.jobsnexgen.com,https://jobsnexgen.com",
        FRONTEND_URL: "https://www.jobsnexgen.com",
        DEBUG: "false",
      },
    },
    {
      name: "crm-api",
      cwd: "$REPO/crm/backend",
      script: "$REPO/crm/backend/venv/bin/python",
      args: "-m uvicorn app.main:app --host 127.0.0.1 --port 8001",
      interpreter: "none",
      env: {
        SECRET_KEY: "$CRM_SECRET_KEY",
        CORS_ORIGINS: "https://crm.jobsnexgen.com",
        FRONTEND_URL: "https://crm.jobsnexgen.com",
        DEBUG: "false",
        PORTAL_API_URL: "http://127.0.0.1:8000/api/v1",
        PORTAL_RECRUITER_EMAIL: "$SYNC_RECRUITER_EMAIL",
        PORTAL_RECRUITER_PASSWORD: "$SYNC_RECRUITER_PASSWORD",
      },
    },
    {
      name: "portal-web",
      cwd: "$REPO/frontend",
      script: "$REPO/frontend/node_modules/next/dist/bin/next",
      args: "start -p 3001 -H 127.0.0.1",
    },
    {
      name: "crm-web",
      cwd: "$REPO/crm/frontend",
      script: "$REPO/crm/frontend/node_modules/next/dist/bin/next",
      args: "start -p 3002 -H 127.0.0.1",
    },
  ],
};
ECOSYSTEM
)

step "nginx"
SITE=/etc/nginx/sites-available/jobsnexgen
if sudo grep -q "managed by Certbot" "$SITE" 2>/dev/null; then
  echo "HTTPS is already configured by certbot; leaving $SITE unchanged."
else
  sudo cp "$REPO/deploy/gcp/nginx.conf" "$SITE"
fi
sudo ln -sf "$SITE" /etc/nginx/sites-enabled/jobsnexgen
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl reload nginx

step "Build and start the apps (takes several minutes)"
bash "$REPO/deploy/gcp/update.sh" --no-pull

step "Start the apps on boot"
sudo env PATH="$PATH" pm2 startup systemd -u "$USER" --hp "$HOME" >/dev/null
pm2 save

step "Waiting for the apps to answer"
for port in 8000 8001 3001 3002; do
  for _ in $(seq 1 30); do
    curl -s -o /dev/null "http://127.0.0.1:$port/" && break
    sleep 2
  done
done

step "Accounts"
(cd "$REPO/backend" && ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_PASSWORD="$PORTAL_ADMIN_PASSWORD" \
  ADMIN_NAME="JobsNexGen Admin" venv/bin/python -m scripts.seed_platform_admin)

register() {  # $1 = label, $2 = URL, $3 = JSON body
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$2" -H 'Content-Type: application/json' -d "$3" || true)
  case "$code" in
    201) echo "$1: created" ;;
    400|403) echo "$1: already exists" ;;
    *) echo "$1: unexpected HTTP $code"; return 1 ;;
  esac
}
# Portal recruiter the CRM logs in as to sync jobs, candidates and applications
register "Portal recruiter for CRM sync" http://127.0.0.1:8000/api/v1/auth/register \
  "{\"name\":\"CRM Sync\",\"email\":\"$SYNC_RECRUITER_EMAIL\",\"password\":\"$SYNC_RECRUITER_PASSWORD\",\"role\":\"recruiter\",\"company_name\":\"JobsNexGen\"}"
# The first CRM sign-up becomes the owner and closes public registration
register "CRM owner" http://127.0.0.1:8001/api/v1/auth/register \
  "{\"name\":\"JobsNexGen Owner\",\"email\":\"$ADMIN_EMAIL\",\"password\":\"$CRM_OWNER_PASSWORD\"}"

step "Smoke test through nginx"
failed=0
check() {  # $1 = host, $2 = path, $3 = expected HTTP codes (regex)
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' -H "Host: $1" "http://127.0.0.1$2" || true)
  if [[ "$code" =~ ^($3)$ ]]; then echo "  ok    $code  $1$2"; else echo "  FAIL  $code  $1$2"; failed=1; fi
}
check jobsnexgen.com     /                  301
check www.jobsnexgen.com /                  200
check www.jobsnexgen.com /jobs              200
check www.jobsnexgen.com /api/v1/jobs       200
check crm.jobsnexgen.com /login             200
check crm.jobsnexgen.com /api/v1/users/me   '401|403'

IP=$(curl -s -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip || true)
cat <<SUMMARY

==========================================================================
 Setup finished.$( [ "$failed" = 0 ] || echo "  Some smoke tests FAILED; check: pm2 logs --lines 50" )
 Server IP: $IP

 Next: at Hostinger, point A records for @, www and crm to $IP,
 then run:  bash deploy/gcp/enable-https.sh $ADMIN_EMAIL

 Logins (also kept in $CONF/secrets.env):
   Job portal admin   https://www.jobsnexgen.com/auth/signin
                      $ADMIN_EMAIL  /  $PORTAL_ADMIN_PASSWORD
   CRM owner          https://crm.jobsnexgen.com/login
                      $ADMIN_EMAIL  /  $CRM_OWNER_PASSWORD
==========================================================================
SUMMARY
